<?php
define('SESSION_PROFILE_ID', 'SESSION_PROFILE_ID');
define('SESSION_LOCALUSER_ID', 'SESSION_LOCALUSER_ID');
define('SESSION_PROFILE_DISPLAYNAME', 'SESSION_PROFILE_DISPLAYNAME');
define('SESSION_PROFILE_ISEMAILVERIFIED', 'SESSION_PROFILE_ISEMAILVERIFIED');
define('SESSION_USER_ISADMINISTRATOR', 'SESSION_USER_ISADMINISTRATOR');
?>